table hospital
	lineageTag: 32f58327-e0f3-587d-a6c8-783c375c36bc

	measure Hospitals = CALCULATE ( COUNTROWS ( hospital ), KEEPFILTERS ( hospital[in_latest] = 1 ) )
		formatString: #,0
		displayFolder: Core
		lineageTag: 207c29cb-2d16-586f-900e-625d2689eb51

	measure Short = CALCULATE ( SUM ( hospital[not_met] ), KEEPFILTERS ( hospital[in_latest] = 1 ) )
		formatString: #,0
		displayFolder: Core
		lineageTag: d44f20da-ae95-5a69-89dd-e4a48e912cb3

	measure 'Short Share' = DIVIDE ( [Short], [Hospitals] )
		formatString: 0%
		displayFolder: Core
		lineageTag: d28def95-3057-546d-9517-2e4781221f63

	measure 'No EHR Short' = CALCULATE ( [Short], KEEPFILTERS ( hospital[ehr_status] = "No EHR ID reported" ) )
		formatString: #,0
		displayFolder: Core
		lineageTag: e7e7ba89-9b6b-5750-90c8-257882bb0b23

	measure 'No EHR Share' = DIVIDE ( [No EHR Short], [Short] )
		formatString: 0%
		displayFolder: Core
		lineageTag: 316fc12a-5f87-5be5-b581-e8411efed3de

	measure 'Hero Line' =
			VAR _s = ROUND ( [Short Share] * 100, 0 )
			VAR _n = ROUND ( [No EHR Share] * 10, 0 )
			RETURN IF ( ISBLANK ( [Hospitals] ), "No hospitals match these filters.",
			    _s & " in 100 hospitals fell short in 2024" & IF ( [Short] > 0, "; " & _n & " in 10 of those had no certified EHR.", "." ) )
		displayFolder: Hero
		lineageTag: 0cfab191-b7d9-5a67-a0ff-7b6d417b7af1

	measure 'Hero Hospitals' = FORMAT ( [Hospitals], "#,0" )
		displayFolder: Hero
		lineageTag: b0533191-b198-55b2-8390-ce4c35c453bf

	measure 'Hero Short' = FORMAT ( [Short] + 0, "#,0" )
		displayFolder: Hero
		lineageTag: f22d4e81-32ee-554d-af24-1c8427f7d956

	measure 'Hero No EHR' = FORMAT ( [No EHR Short] + 0, "#,0" )
		displayFolder: Hero
		lineageTag: da995a69-d746-5a8a-9a54-5c1110da0de9

	measure Dot = "●"
		displayFolder: Hero
		lineageTag: b45c345e-3e14-57e2-acf3-9b68fc09d4ce

	measure 'Dot Colour' =
			VAR _i = SELECTEDVALUE ( Dots[row] ) * 10 + SELECTEDVALUE ( Dots[col] ) + 1
			VAR _s = ROUND ( [Short Share] * 100, 0 )
			VAR _n = ROUND ( DIVIDE ( [No EHR Short], [Hospitals] ) * 100, 0 )
			RETURN SWITCH ( TRUE (), _i > 100 - _n, "#C4A5FF", _i > 100 - _s, "#FF7A59", "#7FA6FF" )
		displayFolder: Hero
		lineageTag: 1b1cee93-b64d-59db-9c0b-39ad71ed3d8b

	measure 'Size Short' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[size_band] ) ) && SELECTEDVALUE ( hospital[size_band] ) <> "" && [Hospitals] >= 20, [Short Share] )
		formatString: 0%
		displayFolder: Charts
		lineageTag: 6e6fe575-66bd-541f-966d-b8b16ddf232d

	measure 'Size Colour' =
			VAR _t = FILTER ( ADDCOLUMNS ( ALLSELECTED ( hospital[size_band] ), "@v", [Size Short] ), NOT ISBLANK ( [@v] ) )
			RETURN IF ( [Size Short] = MAXX ( _t, [@v] ), "#FF6B47", "#FFB199" )
		displayFolder: Colours
		lineageTag: 9732c11d-d2de-53e3-97b7-99a849abdac8

	measure 'Size Title' =
			VAR _t = FILTER ( ADDCOLUMNS ( VALUES ( hospital[size_band] ), "@v", [Short Share], "@n", [Hospitals] ),
			    [@n] >= 20 && NOT ISBLANK ( [@v] ) && NOT ISBLANK ( hospital[size_band] ) )
			VAR _hi = TOPN ( 1, _t, [@v], DESC )
			VAR _lo = TOPN ( 1, _t, [@v], ASC )
			VAR _h = MAXX ( _hi, hospital[size_band] )
			VAR _l = MAXX ( _lo, hospital[size_band] )
			VAR _hp = FORMAT ( MAXX ( _hi, [@v] ), "0%" )
			VAR _lp = FORMAT ( MAXX ( _lo, [@v] ), "0%" )
			RETURN IF ( COUNTROWS ( _t ) < 2, "Share falling short by number of beds", "Hospitals with " & IF ( LEFT ( _h, 5 ) = "Under", LOWER ( _h ), _h & " beds" ) & " fall short most (" & _hp & "), those with " & IF ( LEFT ( _l, 5 ) = "Under", LOWER ( _l ), _l & " beds" ) & " least (" & _lp & ")" )
		displayFolder: Titles
		lineageTag: 18aaf1b0-11c6-55d4-b0b7-170a2601e27e

	measure 'Owner Short' = IF ( [Hospitals] >= 50, [Short Share] )
		formatString: 0%
		displayFolder: Charts
		lineageTag: d21f2626-4c56-5404-9f39-7abe102ef60a

	measure 'Owner Colour' =
			VAR _t = FILTER ( ADDCOLUMNS ( ALLSELECTED ( hospital[ownership] ), "@v", [Owner Short] ), NOT ISBLANK ( [@v] ) )
			RETURN IF ( [Owner Short] = MINX ( _t, [@v] ), "#FFB199", "#FF6B47" )
		displayFolder: Colours
		lineageTag: 0b4410d1-620d-57eb-b835-3633c9e7b618

	measure 'Owner Title' =
			VAR _t = FILTER ( ADDCOLUMNS ( VALUES ( hospital[ownership] ), "@v", [Short Share], "@n", [Hospitals] ),
			    [@n] >= 50 && NOT ISBLANK ( [@v] ) && NOT ISBLANK ( hospital[ownership] ) )
			VAR _hi = TOPN ( 1, _t, [@v], DESC )
			VAR _lo = TOPN ( 1, _t, [@v], ASC )
			VAR _h = MAXX ( _hi, hospital[ownership] )
			VAR _l = MAXX ( _lo, hospital[ownership] )
			VAR _hp = FORMAT ( MAXX ( _hi, [@v] ), "0%" )
			VAR _lp = FORMAT ( MAXX ( _lo, [@v] ), "0%" )
			RETURN IF ( COUNTROWS ( _t ) < 2, "Share falling short by owner", _h & " hospitals fall short most (" & _hp & "), " & LOWER ( _l ) & " hospitals least (" & _lp & ")" )
		displayFolder: Titles
		lineageTag: c456515d-543c-5b37-b2ff-96d99a2a2503

	measure 'Type Hospitals' = [Hospitals]
		formatString: #,0
		displayFolder: Charts
		lineageTag: f5d52139-7c6b-5861-9856-368133c80ba8

	measure 'Type Short' = [Short]
		formatString: #,0
		displayFolder: Charts
		lineageTag: 2f27e40a-84e7-58eb-b913-4ef2360674c3

	measure 'Pair Title' =
			VAR _a = DIVIDE ( CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[hospital_type] = "Small rural (critical access)" ) ), [Hospitals] )
			VAR _b = DIVIDE ( CALCULATE ( [Short], KEEPFILTERS ( hospital[hospital_type] = "Small rural (critical access)" ) ), [Short] )
			RETURN IF ( ISBLANK ( _a ) || ISBLANK ( _b ) || _a = 1, "Who the hospitals that fell short are",
			    "Small rural: " & FORMAT ( _a, "0%" ) & " of hospitals, but " & FORMAT ( _b, "0%" ) & " of those falling short" )
		displayFolder: Titles
		lineageTag: fc0b698f-583f-5ac8-a60a-176450000d6b

	measure 'Market Share' =
			VAR _d = SELECTEDVALUE ( hospital[main_developer] )
			VAR _all = CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[main_developer], hospital[ehr_group] ), NOT ISBLANK ( hospital[main_developer] ) )
			RETURN IF ( NOT ISBLANK ( _d ), DIVIDE ( CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[ehr_group] ) ), _all ) )
		formatString: 0%
		displayFolder: EHR
		lineageTag: 3f59064c-4c33-5fce-8e00-98344877d903

	measure 'Top3 Share' =
			DIVIDE ( CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[ehr_group] ), hospital[main_developer] IN { "Epic", "Oracle Health (Cerner)", "MEDITECH" } ),
			    CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[ehr_group] ), NOT ISBLANK ( hospital[main_developer] ) ) )
		formatString: 0%
		displayFolder: KPI
		lineageTag: f04b8045-4df7-5279-ae18-4449a82ed252

	measure 'Top3 Context' =
			"Epic alone: " & FORMAT ( DIVIDE ( CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[ehr_group] ), hospital[main_developer] = "Epic" ),
			    CALCULATE ( [Hospitals], REMOVEFILTERS ( hospital[ehr_group] ), NOT ISBLANK ( hospital[main_developer] ) ) ), "0%" ) & " of hospitals"
		displayFolder: KPI
		lineageTag: fee96237-12cc-5766-8602-727407efeeed

	measure 'Market Colour' = IF ( SELECTEDVALUE ( hospital[main_developer] ) IN { "Epic", "Oracle Health (Cerner)", "MEDITECH" }, "#5CC8FF", "#6E7FA3" )
		displayFolder: Colours
		lineageTag: 158e1e8c-2214-5040-be28-3fcfdeb2eba7

	measure 'Market Title' = "Epic, Oracle Health and MEDITECH run " & FORMAT ( [Top3 Share], "0%" ) & " of the hospitals shown"
		displayFolder: Titles
		lineageTag: a0977fb2-10e8-518f-ae14-897e7b816265

	measure 'Epic Short' = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[ehr_group] = "Epic" ) )
		formatString: 0.0%
		displayFolder: KPI
		lineageTag: abf529bb-dc72-5b2c-b965-6f8924e73b09

	measure 'Epic Context' =
			VAR _n = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[ehr_group] = "Epic" ) )
			RETURN IF ( ISBLANK ( _n ), "no Epic hospitals in this selection", FORMAT ( CALCULATE ( [Short] + 0, KEEPFILTERS ( hospital[ehr_group] = "Epic" ) ), "#,0" ) & " of " & FORMAT ( _n, "#,0" ) & " hospitals" )
		displayFolder: KPI
		lineageTag: 5de5d85f-595a-53e7-ada3-32fab558e619

	measure 'TruBridge Short' = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[ehr_group] = "TruBridge (CPSI)" ) )
		formatString: 0.0%
		displayFolder: KPI
		lineageTag: 0ca043e7-3605-58dc-a03b-a0edda1f36a6

	measure 'TruBridge Context' =
			VAR _n = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[ehr_group] = "TruBridge (CPSI)" ) )
			RETURN IF ( ISBLANK ( _n ), "no TruBridge hospitals in this selection", FORMAT ( CALCULATE ( [Short] + 0, KEEPFILTERS ( hospital[ehr_group] = "TruBridge (CPSI)" ) ), "#,0" ) & " of " & FORMAT ( _n, "#,0" ) & " hospitals" )
		displayFolder: KPI
		lineageTag: 28b157ce-ad1c-5832-ba63-b15fd008e77c

	measure 'No EHR Hospitals' = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[ehr_status] = "No EHR ID reported" ) )
		formatString: #,0
		displayFolder: KPI
		lineageTag: fc56f583-0907-5fc9-aa5b-2085fc7fca03

	measure 'No EHR All Context' = "all of them fell short"
		displayFolder: KPI
		lineageTag: 54acfba1-2314-536e-b8c5-73c1073608e0

	measure 'EHR Short' = IF ( [Hospitals] >= 40 && NOT ISBLANK ( SELECTEDVALUE ( hospital[ehr_group] ) ) && SELECTEDVALUE ( hospital[ehr_group] ) <> "Other or not identified", [Short Share] )
		formatString: 0%
		displayFolder: EHR
		lineageTag: 7fe60c29-9e4e-5273-af06-987c315008cd

	measure 'EHR Colour' = IF ( SELECTEDVALUE ( hospital[ehr_group] ) = "No EHR ID reported", "#A78BFA", "#FF6B47" )
		displayFolder: Colours
		lineageTag: a1792baf-ae7d-5f62-8b11-16fe653663fa

	measure 'EHR Title' =
			VAR _t = FILTER ( ADDCOLUMNS ( VALUES ( hospital[ehr_group] ), "@v", [Short Share], "@n", [Hospitals] ),
			    [@n] >= 40 && NOT ISBLANK ( [@v] ) && NOT ISBLANK ( hospital[ehr_group] ) && NOT hospital[ehr_group] = "No EHR ID reported" && NOT hospital[ehr_group] = "Other or not identified" )
			VAR _hi = TOPN ( 1, _t, [@v], DESC )
			VAR _lo = TOPN ( 1, _t, [@v], ASC )
			VAR _h = MAXX ( _hi, hospital[ehr_group] )
			VAR _l = MAXX ( _lo, hospital[ehr_group] )
			VAR _hp = FORMAT ( MAXX ( _hi, [@v] ), "0%" )
			VAR _lp = FORMAT ( MAXX ( _lo, [@v] ), "0%" )
			RETURN IF ( COUNTROWS ( _t ) < 2, "Share falling short by EHR company", _h & " hospitals fall short most (" & _hp & "), " & _l & " least (" & _lp & ")" )
		displayFolder: Titles
		lineageTag: 2b2c33dd-3519-590e-b6fa-70d8c4c7666d

	measure 'Vendor Type Short' = IF ( SELECTEDVALUE ( hospital[ehr_group] ) IN { "Epic", "Oracle Health (Cerner)", "MEDITECH", "TruBridge (CPSI)" } && [Hospitals] >= 20, [Short Share] )
		formatString: 0%
		displayFolder: EHR
		lineageTag: 24663b00-a795-581a-81f9-ea5ef8443113

	measure 'Matrix Title' =
			VAR _t = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[ehr_group] = "TruBridge (CPSI)" ), KEEPFILTERS ( hospital[hospital_type] = "Small rural (critical access)" ) )
			VAR _e = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[ehr_group] = "Epic" ), KEEPFILTERS ( hospital[hospital_type] = "Small rural (critical access)" ) )
			RETURN IF ( ISBLANK ( _t ) || ISBLANK ( _e ), "Share falling short by EHR company, small rural vs general hospitals",
			    "Same kind of hospital: small rural ones fall short " & FORMAT ( _t, "0%" ) & " on TruBridge, " & FORMAT ( _e, "0%" ) & " on Epic" )
		displayFolder: Titles
		lineageTag: d2ecf9de-832d-597c-acfe-03aba01e2481

	measure 'Fifth Short' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[margin_fifth] ) ) && [Hospitals] >= 20, [Short Share] )
		formatString: 0%
		displayFolder: Money
		lineageTag: 8a64259c-9aa9-5aec-8e77-2bd636e6141d

	measure 'Fifth Colour' = IF ( SELECTEDVALUE ( hospital[margin_fifth] ) = 1, "#FF6B47", "#FFB199" )
		displayFolder: Colours
		lineageTag: a3cfd86e-9563-51b5-99cc-1cf62850d9db

	measure 'Least Profitable Short' = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[margin_fifth] = 1 ) )
		formatString: 0%
		displayFolder: KPI
		lineageTag: 8e039ad2-71ce-5503-8187-6f782d32da18

	measure 'Least Profitable Context' =
			VAR _b = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[margin_fifth] = 5 ) )
			RETURN IF ( ISBLANK ( _b ), "least profitable fifth of hospitals", "vs " & FORMAT ( _b, "0%" ) & " for the most profitable" )
		displayFolder: KPI
		lineageTag: 7194628e-766f-5fdc-9c24-cec53f907bf9

	measure 'Fifth Title' =
			VAR _a = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[margin_fifth] = 1 ) )
			VAR _b = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[margin_fifth] = 5 ) )
			RETURN IF ( ISBLANK ( _a ) || ISBLANK ( _b ), "Share falling short by profit",
			    "The least profitable fall short most (" & FORMAT ( _a, "0%" ) & "), the most profitable " & FORMAT ( _b, "0%" ) )
		displayFolder: Titles
		lineageTag: c7e465f3-bd0e-5890-ae48-04c5d8d6d28a

	measure 'Money Short' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[lost_money] ) ) && [Hospitals] >= 20, [Short Share] )
		formatString: 0%
		displayFolder: Money
		lineageTag: 1b1f8872-0bd3-5303-a09a-09197ec791be

	measure 'Losses Short' = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[lost_money] = "Lost money 2 years in a row" ) )
		formatString: 0%
		displayFolder: KPI
		lineageTag: e7242d9f-6224-58a9-8c73-988d6aa1f811

	measure 'Losses Context' =
			VAR _b = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[lost_money] = "Did not" ) )
			RETURN IF ( ISBLANK ( _b ), "of hospitals that lost money", "vs " & FORMAT ( _b, "0%" ) & " of those without losses" )
		displayFolder: KPI
		lineageTag: df9974be-afc8-5ae6-b956-6c9f315367bb

	measure 'Money Title' =
			VAR _a = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[lost_money] = "Lost money 2 years in a row" ) )
			VAR _b = CALCULATE ( [Short Share], KEEPFILTERS ( hospital[lost_money] = "Did not" ) )
			RETURN IF ( ISBLANK ( _a ) || ISBLANK ( _b ) || _b = 0, "Share falling short, by whether the hospital lost money",
			    "Hospitals that lost money two years in a row fall short " & FORMAT ( DIVIDE ( _a, _b ), "0.0" ) & " times as often" )
		displayFolder: Titles
		lineageTag: 6c22e26a-b369-5098-9d7f-e956aae603b9

	measure 'History Count' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[history] ) ), [Hospitals] )
		formatString: #,0
		displayFolder: Money
		lineageTag: 6748f30f-b5a2-5c18-bb6e-8a68b8f7f722

	measure 'History Colour' =
			SWITCH ( SELECTEDVALUE ( hospital[history] ), "Never", "#5B8DEF", "Every year", "#C2321A",
			    "1 of 6 years", "#FFB199", "2 of 6 years", "#FFB199", "#FF6B47" )
		displayFolder: Colours
		lineageTag: 0191c9f0-8dd2-50db-8bf5-003ec9ac7a06

	measure 'Every Year' = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[history] = "Every year" ) )
		formatString: #,0
		displayFolder: KPI
		lineageTag: 29486118-0d51-5266-9104-b8d0c9ab172e

	measure 'Every Year Context' = "hospitals, in all six yearly files"
		displayFolder: KPI
		lineageTag: 0b75d78e-c92b-52ce-944d-4c9ffea0a6a2

	measure Never = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[history] = "Never" ) )
		formatString: #,0
		displayFolder: KPI
		lineageTag: 07deb3e9-7fab-577f-8a24-ad01c5b65ebc

	measure 'Never Context' = "of " & FORMAT ( CALCULATE ( [Hospitals], NOT ISBLANK ( hospital[history] ) ), "#,0" ) & " in all six yearly files"
		displayFolder: KPI
		lineageTag: 7b49a20e-cd48-56e9-912c-3b69eab0f887

	measure 'History Title' =
			IF ( ISBLANK ( [Never] ) && ISBLANK ( [Every Year] ), "How many of the six years hospitals fell short",
			    FORMAT ( [Never] + 0, "#,0" ) & " hospitals never fell short; " & FORMAT ( [Every Year] + 0, "#,0" ) & " fell short every single year" )
		displayFolder: Titles
		lineageTag: 2caa2747-b826-59e5-9129-147922a205a4

	measure 'Top 10 Share' =
			VAR _cur = [Short Share]
			VAR _n = [Hospitals]
			VAR _all = CALCULATETABLE ( FILTER ( ADDCOLUMNS ( VALUES ( states[state_name] ), "@r", [Short Share], "@n", [Hospitals] ), [@n] >= 10 ), REMOVEFILTERS ( states ) )
			RETURN IF ( HASONEVALUE ( states[state_name] ) && _n >= 10 && COUNTROWS ( FILTER ( _all, [@r] > _cur ) ) < 10, _cur )
		formatString: 0%
		displayFolder: States
		lineageTag: 6178c13f-7509-51ba-a38b-1bf7b3023db8

	measure 'Top 10 Hospitals' = IF ( NOT ISBLANK ( [Top 10 Share] ), [Hospitals] )
		formatString: #,0
		displayFolder: States
		lineageTag: 749938ef-a39e-5d71-b5a2-0550efbaa1e4

	measure 'Top 10 Short' = IF ( NOT ISBLANK ( [Top 10 Share] ), [Short] )
		formatString: #,0
		displayFolder: States
		lineageTag: c2fd16f1-597e-53d8-9e2e-779f75611d18

	measure 'Tile Label' = SELECTEDVALUE ( states[state] )
		displayFolder: Map
		lineageTag: 980bf1f0-0c38-51a3-9e2e-0d40afe83f76

	measure 'Tile Colour' =
			VAR _r = [Short Share]
			RETURN SWITCH ( TRUE (),
			    ISBLANK ( SELECTEDVALUE ( states[state] ) ), "#0E2259",
			    ISBLANK ( _r ), "#2A3E78",
			    _r < 0.05, "#FDF0EA",
			    _r < 0.10, "#F9CDBB",
			    _r < 0.15, "#F29A78",
			    _r < 0.25, "#FF6B47",
			    "#C2321A" )
		displayFolder: Map
		lineageTag: 1ba12b64-6996-586d-909e-37dcc04202f1

	measure 'Tile Font' = IF ( [Short Share] >= 0.15 || ISBLANK ( [Short Share] ), "#FFFFFF", "#141B2D" )
		displayFolder: Map
		lineageTag: 594ee0e2-effb-55fe-af90-cb0e6cb58b9a

	measure 'Fifth States' = COUNTROWS ( FILTER ( CALCULATETABLE ( ADDCOLUMNS ( VALUES ( states[state] ), "@r", [Short Share], "@n", [Hospitals] ), REMOVEFILTERS ( states ) ), [@n] >= 10 && [@r] >= 0.2 ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: eeca6a31-d143-5ef7-a136-b4a397546710

	measure 'Zero States' = COUNTROWS ( FILTER ( CALCULATETABLE ( ADDCOLUMNS ( VALUES ( states[state] ), "@s", [Short] + 0, "@n", [Hospitals] ), REMOVEFILTERS ( states ) ), [@n] >= 10 && [@s] = 0 ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: 6ab6fb3e-77f2-5e2b-8c27-278a37fe0775

	measure 'Map Title' =
			VAR _t = TOPN ( 1, FILTER ( CALCULATETABLE ( ADDCOLUMNS ( VALUES ( states[state_name] ), "@r", [Short Share], "@n", [Hospitals] ), REMOVEFILTERS ( states ) ), [@n] >= 10 ), [@r], DESC )
			RETURN IF ( ISBLANK ( MAXX ( _t, [@r] ) ), "Share of hospitals falling short, by state",
			    MAXX ( _t, states[state_name] ) & " has the highest share falling short: " & FORMAT ( MAXX ( _t, [@r] ), "0%" ) & " of its hospitals" )
		displayFolder: Titles
		lineageTag: d0558e03-744a-5f63-8909-97665fa09dd3

	measure 'Selected State' = SELECTEDVALUE ( states[state_name], "All states" )
		displayFolder: Tooltip
		lineageTag: eac3fece-e636-5520-a82e-ee4fbb15fb71

	measure 'State Rank Text' =
			VAR _cur = [Short Share]
			VAR _all = CALCULATETABLE ( FILTER ( ADDCOLUMNS ( VALUES ( states[state_name] ), "@r", [Short Share], "@n", [Hospitals] ), [@n] >= 10 ), REMOVEFILTERS ( states ) )
			RETURN IF ( HASONEVALUE ( states[state_name] ) && [Hospitals] >= 10, "#" & COUNTROWS ( FILTER ( _all, [@r] > _cur ) ) + 1 & " of "
			    & COUNTROWS ( _all ) & " for the share falling short", "Too few hospitals to rank" )
		displayFolder: Tooltip
		lineageTag: a8ad20cc-11bc-50b2-8062-97076eaddee0

	measure 'State Short Text' = FORMAT ( [Short] + 0, "#,0" ) & " of " & FORMAT ( [Hospitals], "#,0" ) & " hospitals"
		displayFolder: Tooltip
		lineageTag: dde787c3-3b44-5dca-b748-eaee639de9a4

	measure 'State No EHR' = FORMAT ( [No EHR Short] + 0, "#,0" ) & " had no certified EHR"
		displayFolder: Tooltip
		lineageTag: 2025817f-63ad-55ad-8c78-341518be707a

	measure 'ID Count' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[id_quality] ) ), [Hospitals] )
		formatString: #,0
		displayFolder: Quality
		lineageTag: 70043fd6-b4c4-58e2-a093-0c7ef9b31adc

	measure 'ID Colour' =
			SWITCH ( SELECTEDVALUE ( hospital[id_quality] ),
			    "Valid ID, found in the federal list", "#6E7FA3",
			    """Not Available"" typed instead of an ID", "#A78BFA",
			    "#FBBF24" )
		displayFolder: Colours
		lineageTag: ad35a331-37a4-52ed-8de4-d11ba50888ee

	measure 'Not Available Count' = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[id_quality] = """Not Available"" typed instead of an ID" ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: b62a0561-b5e6-5558-a56c-d55d9b15f09d

	measure 'Not In List Count' = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[id_quality] = "Not found in the federal list" ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: bf0126e6-9af7-5737-a967-a698e59fa4e7

	measure 'Bad Format Count' = CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[id_quality] = "Wrong format (lowercase or wrong length)" ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: 1d87c8b9-0b8d-5fbe-9986-916d04408cfb

	measure 'Disagree Count' = CALCULATE ( SUM ( hospital[files_disagree] ), KEEPFILTERS ( hospital[in_latest] = 1 ) ) + 0
		formatString: #,0
		displayFolder: KPI
		lineageTag: a95eec4e-69ba-50fd-9e70-639dc5935532

	measure 'Not Available Context' = "hospitals, and every one fell short"
		displayFolder: KPI
		lineageTag: 521c2fb8-0ce6-51f6-9a42-64b94aae9bb8

	measure 'Not In List Context' = "IDs missing from the federal list"
		displayFolder: KPI
		lineageTag: 50a6317e-c4ac-55a8-9423-c4f543ec2f54

	measure 'Bad Format Context' = "lowercase or wrong length"
		displayFolder: KPI
		lineageTag: a84a08c1-aba3-5a09-ba14-63c816d98729

	measure 'Disagree Context' = "hospitals rated differently"
		displayFolder: KPI
		lineageTag: 94d19fef-10d2-540b-af39-49eddc1a738c

	measure 'Disagree Count By Type' = IF ( NOT ISBLANK ( SELECTEDVALUE ( hospital[disagree_type] ) ), [Disagree Count] )
		formatString: #,0
		displayFolder: Quality
		lineageTag: 5c084d6f-bcd0-5f5e-9f38-eed5d7340662

	measure 'Files Count' = IF ( SELECTEDVALUE ( hospital[n_files] ) > 0, COUNTROWS ( hospital ) )
		formatString: #,0
		displayFolder: Quality
		lineageTag: 7a0f7e5d-21ea-57c4-a54f-47e175e8f8a6

	measure 'Files Colour' = IF ( SELECTEDVALUE ( hospital[n_files] ) = 6, "#6E7FA3", "#FBBF24" )
		displayFolder: Colours
		lineageTag: d4af2e87-30d3-50ac-bd00-0ebae1fd004e

	measure 'ID Title' =
			VAR _p = DIVIDE ( [Hospitals] - CALCULATE ( [Hospitals], KEEPFILTERS ( hospital[id_quality] = "Valid ID, found in the federal list" ) ), [Hospitals] )
			RETURN IF ( ISBLANK ( _p ), "What hospitals put in the EHR ID field", FORMAT ( ROUND ( _p * 100, 0 ), "0" ) & " in 100 hospitals have a problem in the EHR ID field" )
		displayFolder: Titles
		lineageTag: b72adf08-51a7-55ac-82e8-f420e763dde9

	measure 'Disagree Title' = FORMAT ( [Disagree Count], "#,0" ) & " hospitals get a different answer in the two Medicare files"
		displayFolder: Titles
		lineageTag: 88576335-2f60-59b3-aac3-f5616fb46893

	measure 'Files Title' =
			VAR _a = CALCULATE ( COUNTROWS ( hospital ), KEEPFILTERS ( hospital[n_files] = 6 ) )
			VAR _b = CALCULATE ( COUNTROWS ( hospital ), KEEPFILTERS ( hospital[n_files] > 0 ) )
			RETURN FORMAT ( _a + 0, "#,0" ) & " of " & FORMAT ( _b + 0, "#,0" ) & " hospitals appear in all six yearly files"
		displayFolder: Titles
		lineageTag: 4317619c-01c1-58df-9ab8-51fe966677be

	measure 'Top3 Share Text' =
			VAR _v = [Top3 Share]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "0%" ) )
		displayFolder: KPI text
		lineageTag: 28e143d7-72bd-5299-9753-1d21afd0ecdd

	measure 'Epic Short Text' =
			VAR _v = [Epic Short]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "0.0%" ) )
		displayFolder: KPI text
		lineageTag: 73920a46-d1f5-54dd-840d-864d28269d16

	measure 'TruBridge Short Text' =
			VAR _v = [TruBridge Short]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "0.0%" ) )
		displayFolder: KPI text
		lineageTag: 3b13cc02-7900-53fe-9a13-0d36a2023b8e

	measure 'No EHR Hospitals Text' =
			VAR _v = [No EHR Hospitals]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 9bf7843d-4434-5575-98a2-9fc945ad665c

	measure 'Least Profitable Short Text' =
			VAR _v = [Least Profitable Short]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "0%" ) )
		displayFolder: KPI text
		lineageTag: dcd2cc68-4cb7-5ad0-874b-e77e56dc7d8f

	measure 'Losses Short Text' =
			VAR _v = [Losses Short]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "0%" ) )
		displayFolder: KPI text
		lineageTag: 6ab1bb3e-d77a-5cf6-b6d7-d8150158b4a6

	measure 'Every Year Text' =
			VAR _v = [Every Year]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: bf291e59-674f-5e78-9d11-c197cfdca761

	measure 'Never Text' =
			VAR _v = [Never]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 26f6b8c9-8199-5376-acbc-7d799d942f6c

	measure 'Fifth States Text' =
			VAR _v = [Fifth States]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: f87e6ce1-1edd-5193-bb2f-ba877dd1849c

	measure 'Zero States Text' =
			VAR _v = [Zero States]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 12999251-573b-552e-af02-016b88e183b1

	measure 'Not Available Count Text' =
			VAR _v = [Not Available Count]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 16cfff49-37f8-5d41-8dea-b82f369b353a

	measure 'Not In List Count Text' =
			VAR _v = [Not In List Count]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 0da9606d-f54f-5d88-b39c-f240c2889f8e

	measure 'Bad Format Count Text' =
			VAR _v = [Bad Format Count]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: f66e8a43-8c36-56b1-8872-27c0b9ca4592

	measure 'Disagree Count Text' =
			VAR _v = [Disagree Count]
			RETURN IF ( ISBLANK ( _v ), "–", FORMAT ( _v, "#,0" ) )
		displayFolder: KPI text
		lineageTag: 8c934f4a-cd1d-58d9-8d14-cb67c9af183e

	measure 'Profile Name' = IF ( HASONEVALUE ( hospital[hospital_label] ), SELECTEDVALUE ( hospital[display_name] ), "Pick a hospital" )
		displayFolder: Hospital
		lineageTag: 765a32db-c40e-5514-bbad-0cda3eaf30f8

	measure 'Profile Facts' = IF ( HASONEVALUE ( hospital[hospital_label] ), SELECTEDVALUE ( hospital[hospital_type] ) & "   ·   " & SELECTEDVALUE ( hospital[ownership] ) & "   ·   " & SELECTEDVALUE ( hospital[city] ) & ", " & SELECTEDVALUE ( hospital[state_name] ) & IF ( NOT ISBLANK ( SUM ( hospital[beds] ) ), "   ·   " & FORMAT ( SUM ( hospital[beds] ), "#,0" ) & " beds" ), "Type a hospital name in the search box on the right" )
		displayFolder: Hospital
		lineageTag: d61895b8-09eb-5178-b39a-3e6b0b9b2cda

	measure 'Profile Status' = IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( SUM ( hospital[in_latest] ) = 0, "Not in the 2024 file", IF ( SUM ( hospital[not_met] ) = 1, "Fell short", "Met the standards" ) ) )
		displayFolder: Hospital
		lineageTag: 74f79ff6-4470-564d-844e-80c64a084f93

	measure 'Profile Status Colour' = IF ( SUM ( hospital[not_met] ) = 1, "#FF6B47", "#5B8DEF" )
		displayFolder: Hospital
		lineageTag: 78758bb8-0fdc-5ab0-97ab-e5c7c9f41000

	measure 'Profile Status Context' = IF ( HASONEVALUE ( hospital[hospital_label] ), "in the 2024 reporting year" )
		displayFolder: Hospital
		lineageTag: bb09d4ab-5566-5d80-8ff4-389687bf540d

	measure 'Profile EHR' =
			IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( SELECTEDVALUE ( hospital[ehr_status] ) = "No EHR ID reported", "None reported",
			    COALESCE ( SELECTEDVALUE ( hospital[main_developer] ), "Not identified" ) ) )
		displayFolder: Hospital
		lineageTag: 117eed58-4ada-5001-a1aa-ce52189b149d

	measure 'Profile EHR Colour' = IF ( SELECTEDVALUE ( hospital[ehr_status] ) = "No EHR ID reported", "#A78BFA", "#FFFFFF" )
		displayFolder: Hospital
		lineageTag: 910e68f8-59ec-5c3b-a1bc-baab5a49a847

	measure 'Profile EHR Context' =
			VAR _k = SUM ( hospital[hospitals_sharing_ehr_id] ) - 1
			RETURN IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( SELECTEDVALUE ( hospital[ehr_status] ) = "No EHR ID reported", "no certified EHR ID in the 2024 file",
			    IF ( _k > 0, "same EHR setup as " & _k & " other hospital" & IF ( _k > 1, "s", "" ), "its own EHR setup" ) ) )
		displayFolder: Hospital
		lineageTag: 198a2c52-6be2-5bff-9049-705087681e91

	measure 'Profile Years' = IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( COUNTROWS ( hospital_year ) > 0, FORMAT ( SUM ( hospital_year[not_met] ) + 0, "0" ) & " of " & COUNTROWS ( hospital_year ), "No history" ) )
		displayFolder: Hospital
		lineageTag: 98ae0c03-5c64-5f79-9de5-0f43f4ef459d

	measure 'Profile Years Colour' = IF ( SUM ( hospital_year[not_met] ) > 0, "#FF6B47", "#5B8DEF" )
		displayFolder: Hospital
		lineageTag: 8e9486ab-f3f7-5e58-bee1-28b80c4b87cc

	measure 'Profile Years Context' = IF ( HASONEVALUE ( hospital[hospital_label] ), "yearly Medicare files, 2019-2024" )
		displayFolder: Hospital
		lineageTag: e645e2e6-01aa-5145-a07a-0a11181e8326

	measure 'Profile Margin' = IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( ISBLANK ( SUM ( hospital[total_margin] ) ), "No report", FORMAT ( SUM ( hospital[total_margin] ) * 100, "0.0" ) & " cents" ) )
		displayFolder: Hospital
		lineageTag: ce7bdfc6-a1eb-50d2-811d-68aff739d168

	measure 'Profile Margin Colour' = IF ( SUM ( hospital[total_margin] ) < 0, "#FF6B47", "#FFFFFF" )
		displayFolder: Hospital
		lineageTag: f5249ded-f07a-5425-b3d7-7c1949cf614d

	measure 'Profile Margin Context' =
			IF ( HASONEVALUE ( hospital[hospital_label] ), IF ( ISBLANK ( SUM ( hospital[total_margin] ) ), "no financial report matched",
			    "profit kept from each $1" & IF ( SELECTEDVALUE ( hospital[lost_money] ) = "Lost money 2 years in a row", "; lost money 2 years running", "" ) ) )
		displayFolder: Hospital
		lineageTag: 43eb3fdb-0ebb-5839-bc5c-4f7eefbd9e4b

	measure 'Profile Sentence' =
			VAR _t = SELECTEDVALUE ( hospital[hospital_type] )
			VAR _peer = CALCULATE ( [Short Share], REMOVEFILTERS ( hospital ), REMOVEFILTERS ( states ), hospital[hospital_type] = _t )
			VAR _short = SUM ( hospital[not_met] ) = 1
			VAR _y = SUM ( hospital_year[not_met] ) + 0
			VAR _n = COUNTROWS ( hospital_year )
			RETURN IF ( HASONEVALUE ( hospital[hospital_label] ) && SUM ( hospital[in_latest] ) = 1,
			    "In 2024 this hospital " & IF ( _short, "did not meet", "met" ) & " Medicare's standards for sharing health records electronically. "
			    & FORMAT ( _peer, "0%" ) & IF ( _t = "General hospital", " of general hospitals", " of small rural hospitals" ) & " fell short. "
			    & IF ( _n > 0, "It fell short in " & _y & " of the " & _n & " yearly files since 2019"
			        & IF ( _y = 0, ": a steady record.", IF ( _y = _n, ": it has never met them.", "." ) ), "" )
			    & IF ( SELECTEDVALUE ( hospital[ehr_status] ) = "No EHR ID reported", " It reported no certified EHR, the most common reason hospitals fall short.", "" ),
			    IF ( HASONEVALUE ( hospital[hospital_label] ), "This hospital is not in the latest Medicare file (it may have closed or merged).", "Pick a hospital to see what its numbers mean." ) )
		displayFolder: Hospital
		lineageTag: e0f4041f-0cb1-5f76-9afc-e4e585536705

	measure 'Profile Checks' =
			IF ( HASONEVALUE ( hospital[hospital_label] ) && SUM ( hospital[in_latest] ) = 1, "EHR ID field: " & SELECTEDVALUE ( hospital[id_quality] ) & ". "
			    & IF ( SUM ( hospital[files_disagree] ) = 1, "The two Medicare files give different answers for this hospital.",
			         "The Medicare files agree on its status." ) )
		displayFolder: Hospital
		lineageTag: f0e329e6-e502-5984-b922-bc461c15a414

	column ccn
		dataType: string
		isHidden
		lineageTag: dcbe1156-c3c7-5e60-9048-cf1a51f9e935
		summarizeBy: none
		sourceColumn: ccn

		annotation SummarizationSetBy = Automatic

	column hospital_label
		dataType: string
		lineageTag: 41c07a3b-166c-5571-ab98-629c12f8a7d8
		summarizeBy: none
		sourceColumn: hospital_label

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: 613bc6fd-2ac7-5266-b625-12009a62ad61
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 9a642472-64f1-58c7-94e6-113849cb1d77
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 025e8e1c-c567-538a-97aa-46272b32a1f0
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: 6c4b2296-f8b8-53d2-a5b8-a4a9b8b29d4a
		summarizeBy: none
		sourceColumn: state_name

		annotation SummarizationSetBy = Automatic

	column hospital_type
		dataType: string
		lineageTag: aecef6e1-4c4f-5755-af66-1c9dbc4feaaa
		summarizeBy: none
		sourceColumn: hospital_type

		annotation SummarizationSetBy = Automatic

	column ownership
		dataType: string
		lineageTag: c6fee506-4962-55a9-b2c6-d01f487c226f
		summarizeBy: none
		sourceColumn: ownership

		annotation SummarizationSetBy = Automatic

	column rural_urban
		dataType: string
		lineageTag: 7a459809-7421-54bb-aa1e-759cbde168e2
		summarizeBy: none
		sourceColumn: rural_urban

		annotation SummarizationSetBy = Automatic

	column in_latest
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: f18b8406-58ba-5ce7-9783-e9e1254ccc35
		summarizeBy: sum
		sourceColumn: in_latest

		annotation SummarizationSetBy = Automatic

	column not_met
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: e82d7971-23ad-5835-9d2f-64fc4e4a2dd5
		summarizeBy: none
		sourceColumn: not_met

		annotation SummarizationSetBy = Automatic

	column ehr_status
		dataType: string
		lineageTag: 86d72985-29f4-55e5-926b-40c704d3f20d
		summarizeBy: none
		sourceColumn: ehr_status

		annotation SummarizationSetBy = Automatic

	column ehr_group
		dataType: string
		lineageTag: c8a538ca-996b-57ec-b59b-41063c216960
		summarizeBy: none
		sourceColumn: ehr_group

		annotation SummarizationSetBy = Automatic

	column main_developer
		dataType: string
		lineageTag: 4a06af6f-9092-59d7-8897-860984549f95
		summarizeBy: none
		sourceColumn: main_developer

		annotation SummarizationSetBy = Automatic

	column beds
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 95bb1d1f-dc89-55a8-8d73-0833bbc41507
		summarizeBy: none
		sourceColumn: beds

		annotation SummarizationSetBy = Automatic

	column size_band
		dataType: string
		sortByColumn: size_order
		lineageTag: 46326c91-6b50-51f3-bb18-7db8e77f2436
		summarizeBy: none
		sourceColumn: size_band

		annotation SummarizationSetBy = Automatic

	column size_order
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 5db2f717-dd9d-53fc-9295-60bd47288c69
		summarizeBy: none
		sourceColumn: size_order

		annotation SummarizationSetBy = Automatic

	column total_margin
		dataType: double
		formatString: #,0.00
		isHidden
		lineageTag: 5d42625f-0959-5339-a661-006f8946e86e
		summarizeBy: sum
		sourceColumn: total_margin

		annotation SummarizationSetBy = Automatic

	column margin_fifth
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: f64acffb-3f80-5a15-8c27-f973983514a2
		summarizeBy: none
		sourceColumn: margin_fifth

		annotation SummarizationSetBy = Automatic

	column margin_fifth_label
		dataType: string
		sortByColumn: margin_fifth
		lineageTag: a4a2cc8f-4cb1-5b59-8e18-57df003d9e3f
		summarizeBy: none
		sourceColumn: margin_fifth_label

		annotation SummarizationSetBy = Automatic

	column lost_money
		dataType: string
		lineageTag: c2df7615-e391-5491-8261-c85def30a2c4
		summarizeBy: none
		sourceColumn: lost_money

		annotation SummarizationSetBy = Automatic

	column years_reported
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: c36799a6-cbfe-5e5c-b8f1-475467830d34
		summarizeBy: none
		sourceColumn: years_reported

		annotation SummarizationSetBy = Automatic

	column years_not_met
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: d4df536d-dd2d-56aa-8ae4-27c65987efa4
		summarizeBy: none
		sourceColumn: years_not_met

		annotation SummarizationSetBy = Automatic

	column history
		dataType: string
		sortByColumn: history_order
		lineageTag: 4eee3c9c-cb24-5f32-b6f9-7cd94937ef9c
		summarizeBy: none
		sourceColumn: history

		annotation SummarizationSetBy = Automatic

	column history_order
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: d981ff34-ec93-57c2-91c6-39cdbcd157bd
		summarizeBy: none
		sourceColumn: history_order

		annotation SummarizationSetBy = Automatic

	column hospitals_sharing_ehr_id
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 00ffbb07-560f-577f-b096-0c8fac261822
		summarizeBy: none
		sourceColumn: hospitals_sharing_ehr_id

		annotation SummarizationSetBy = Automatic

	column id_quality
		dataType: string
		lineageTag: e7aada9f-e470-52e1-b4c4-b5c8282b0b4d
		summarizeBy: none
		sourceColumn: id_quality

		annotation SummarizationSetBy = Automatic

	column files_disagree
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 9611fdca-0b30-5074-ae2b-d56b52b044b0
		summarizeBy: sum
		sourceColumn: files_disagree

		annotation SummarizationSetBy = Automatic

	column disagree_type
		dataType: string
		lineageTag: fd1f052a-f8fb-5a04-981f-d44443c84361
		summarizeBy: none
		sourceColumn: disagree_type

		annotation SummarizationSetBy = Automatic

	column n_files
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 24a3e560-47f5-518b-8a61-4cd70434ea90
		summarizeBy: sum
		sourceColumn: n_files

		annotation SummarizationSetBy = Automatic

	column finance_match
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 97f94375-4046-5e99-a65b-f26755ced767
		summarizeBy: sum
		sourceColumn: finance_match

		annotation SummarizationSetBy = Automatic

	partition hospital = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "hospital.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // empty CSV cells arrive as "" text; make them real blanks so they drop out of charts
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks,{{"ccn", type text}, {"hospital_label", type text}, {"display_name", type text}, {"city", type text}, {"state", type text}, {"state_name", type text}, {"hospital_type", type text}, {"ownership", type text}, {"rural_urban", type text}, {"in_latest", Int64.Type}, {"not_met", Int64.Type}, {"ehr_status", type text}, {"ehr_group", type text}, {"main_developer", type text}, {"beds", Int64.Type}, {"size_band", type text}, {"size_order", Int64.Type}, {"total_margin", type number}, {"margin_fifth", Int64.Type}, {"margin_fifth_label", type text}, {"lost_money", type text}, {"years_reported", Int64.Type}, {"years_not_met", Int64.Type}, {"history", type text}, {"history_order", Int64.Type}, {"hospitals_sharing_ehr_id", Int64.Type}, {"id_quality", type text}, {"files_disagree", Int64.Type}, {"disagree_type", type text}, {"n_files", Int64.Type}, {"finance_match", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
