table hospital_year
	lineageTag: e4e71fb1-21ff-5e68-a7fc-a35e8bed72e1

	measure 'Year Share' = DIVIDE ( SUM ( hospital_year[not_met] ), COUNTROWS ( hospital_year ) )
		formatString: 0%
		displayFolder: Core
		lineageTag: 09922db0-6e74-5db9-861b-803fab1985bb

	measure 'Trend Title' =
			VAR _a = CALCULATE ( [Year Share], KEEPFILTERS ( hospital_year[snapshot_year] = 2019 ) )
			VAR _b = CALCULATE ( [Year Share], KEEPFILTERS ( hospital_year[snapshot_year] = 2024 ) )
			RETURN IF ( ISBLANK ( _a ) || ISBLANK ( _b ), "Share falling short in each yearly Medicare file",
			    IF ( _b < _a, "Fewer hospitals fall short than in 2019: ", "More hospitals fall short than in 2019: " )
			    & FORMAT ( _a, "0%" ) & " then, " & FORMAT ( _b, "0%" ) & " in 2024" )
		displayFolder: Titles
		lineageTag: 25d8e602-6e29-504e-a19d-07d0bad5090c

	measure 'Rural Year Share' = CALCULATE ( [Year Share], KEEPFILTERS ( hospital_year[year_type] = "Small rural (critical access)" ) )
		formatString: 0%
		displayFolder: Spark
		lineageTag: cf395fe4-b46e-5472-8542-2ce7f0f3c220

	measure 'Strip Value' = IF ( HASONEVALUE ( hospital[hospital_label] ), COUNTROWS ( hospital_year ) )
		formatString: 0
		displayFolder: Hospital
		lineageTag: f8e83886-51de-5066-b9a9-7aeb62704bb7

	measure 'Strip Colour' = IF ( SUM ( hospital_year[not_met] ) = 1, "#D64545", "#1F4E9E" )
		displayFolder: Hospital
		lineageTag: cba660ed-1e86-53be-be01-9363ca8c0dee

	column ccn
		dataType: string
		isHidden
		lineageTag: 5c4d70f5-e598-5171-8176-8b00b022f456
		summarizeBy: none
		sourceColumn: ccn

		annotation SummarizationSetBy = Automatic

	column snapshot_year
		dataType: int64
		formatString: 0
		lineageTag: 6f44a28c-3f72-501d-be81-e1d7b735a321
		summarizeBy: none
		sourceColumn: snapshot_year

		annotation SummarizationSetBy = Automatic

	column year_type
		dataType: string
		lineageTag: d6d695f7-c1cc-5825-9f3b-f245bd18fa73
		summarizeBy: none
		sourceColumn: year_type

		annotation SummarizationSetBy = Automatic

	column not_met
		dataType: int64
		formatString: 0
		isHidden
		lineageTag: 72f10f26-a354-5ea7-bc97-8519fd261cc4
		summarizeBy: none
		sourceColumn: not_met

		annotation SummarizationSetBy = Automatic

	partition hospital_year = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "hospital_year.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // empty CSV cells arrive as "" text; make them real blanks so they drop out of charts
				    Blanks = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Blanks,{{"ccn", type text}, {"snapshot_year", Int64.Type}, {"year_type", type text}, {"not_met", Int64.Type}}, "en-US")
				in
				    Typed

	annotation PBI_ResultType = Table
